encoding: utf-8
ignore_all_files_in_gitignore: true
ignored_paths: []
read_only: false
excluded_tools: []
initial_prompt: ''
project_name: zero2prod
included_optional_tools: []
base_modes: null
default_modes: null
fixed_tools: []
symbol_info_budget: null
language_backend: null
read_only_memory_patterns: []
line_ending: null
ignored_memory_patterns: []
ls_specific_settings: {}
language: rust
